name: Doctest CI
# Run Pywikibot doctests  with a variety of Python versions

on:
  push:
    branches: [ master ]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYWIKIBOT_TEST_RUNNING: 1
  PYWIKIBOT_USERNAME: Pywikibot-test

jobs:
  build:
    runs-on: ${{ matrix.os || 'ubuntu-latest'}}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      max-parallel: 7

      matrix:
        os: [ "windows-latest", "macOS-latest", "ubuntu-latest" ]
        python-version: ["pypy3.7", "3.11"]
        include:
          - python-version: "3.12.0-alpha - 3.12.0"
          # ubuntu-20.04 required for Python 3.6
          - python-version: 3.6
            os: windows-latest
          - python-version: 3.6
            os: macOS-latest
          - python-version: 3.6
            os: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip --version
        pip install -U setuptools
        pip install pytest
        pip install "sseclient<0.0.23,>=0.0.18"
        pip install mwparserfromhell
        pip install "PyMySQL >= 0.9.3"
        pip install codecov
        pip install coverage
        python -c "import setuptools; print('setuptools:', setuptools.__version__)"

    - name: Generate user files
      run: |
        python -Werror::UserWarning -m pwb generate_user_files -site:wikipedia:test -user:${{ env.PYWIKIBOT_USERNAME }} -v -debug;

    - name: doctest with pytest
      timeout-minutes: 10
      run: |
        python pwb.py version
        pytest --version
        coverage run -m pytest pywikibot --doctest-modules --ignore-glob="*gui.py" --ignore-glob="*memento.py"
    - name: Upload coverage to Codecov
      run: codecov
